# Generated by Django 5.2 on 2025-04-24 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True, null=True)),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("apply_link", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
    ]
